sudo: required

language: bash

services:
  - docker

before_install:
    - docker build -t vect0r/hey .

script:
    - docker run --rm vect0r/hey -n 1000 -c 100 https://google.com

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push vect0r/hey;
      fi

